#!/usr/bin/env python3
"""224XL plan-020 Phase 2 — T&C microsequencer FREE-RUN on the POST-passing edge-driven datapath.

FreeRunRTL EXTENDS aru_rtl_dp.ARU_RTL (which passes POST un-suppressed) and adds the free-running T&C
microsequencer: a 7-bit WCS program counter sweeps the microprogram, each step fetches its 32-bit
microword and drives the SAME datapath elements (regfile / gate-Booth MAC / accumulator / result reg /
DMEM / DAB) through the edge-driven DEFERRED MAC built in Phase 1 (ARU_RTL.mac_step). CPC advances once
per sample at RESET; the DMEM recirculates across samples; audio flows A/D → DSP → D/A.

The single-step POST path (ARU_RTL.single_step / _multiply) is INHERITED UNCHANGED — POST stays green.

Phase 2.0 — WCS PC modulus (RESOLVED from netlist §3.5 + SM):
  The PC (tc_U14/U1, 74LS163 pair) is a 7-bit COUNT-ONLY counter (PC0-6): /LD tied high (no preset),
  count-enable = HALT/, and it is SYNC-CLEARED by a WCS-GENERATED RESET (tc_U34 g2 = AND(tcWR, OFST3/)),
  NOT a hardwired count comparator. The Service Manual: "the counter is normally reset at count 99 by a
  RESET signal generated by the WCS itself." So the program sets its own length. Default modulus = 100
  (steps 0..99), matching plan-019's proven 100 microwords + aru_freerun + the SM. Steps 100..127 of the
  0x4000 image are valid structured microwords (candidate shadow / per-frame-modulation region, taps
  107..119) — whether they execute is the residual open question, so `modulus` is a PARAMETER and the
  milestone tests 100 vs 128.

Harvested from aru_freerun (device decode + offset convention are POST-grounded, do not reinvent):
  • §2T device_decode (MEMR/MEMW/RD AD/WR DA/RDRREG/RD XREG + SDAA-D reversed one-hot channels),
  • addr = CPC + ofst + 1 = CPC − OFST (the POST-verified convention),
  • the FPC float↔fixed codec (fpc_input/output_*).
The MAC itself is the edge-driven Phase-1 mac_step (verified to reproduce aru_freerun 200/200), on the
gate-level Booth front-end — NOT the behavioral product20.

Run:  python tools/aru_freerun_rtl.py     (structural self-tests: oracle-match vs aru_freerun + M3 comb)
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from aru_rtl_dp import ARU_RTL, decode, s16, sat16
import aru_freerun as FR         # harvest device_decode, offset convention, FPC codec, DRV_* constants

FS = 34130.0


class FreeRunRTL(ARU_RTL):
    """Free-running ARU+DMEM+T&C on the edge-driven datapath. Same run_sample/run_free interface as
    aru_freerun.FreeRunARU, so tools/aru_whole.py drives either engine through the same capture path."""

    def __init__(self, mem=None, modulus=100, fpc_enabled=False, xfer_gate=None):
        super().__init__(mem if mem is not None else bytearray(0x10000))
        self.modulus = modulus              # WCS PC modulus (Phase 2.0; default 100, RESET@99)
        self.fpc_enabled = fpc_enabled
        # xfer_gate(d, dev) -> bool: OPTIONAL hypothesis test for the "XFER CK strobe gating" the decode
        # flags UNTESTED (netlist §G3T: XFER CK = NAND(AS0, XFER, tc_U25.pin9); the third term is an
        # "unused"-FF output per §3.11, so provisionally constant). None = XFER fires whenever the bit is
        # set (the faithful default). A gate returning False suppresses the result-reg load on that step.
        self.xfer_gate = xfer_gate
        # prot_mode: OPTIONAL hypothesis for PROT (MI22 = l2 bit6), whose downstream effect the netlist
        # leaves UNTRACED (tc_U18.QC → "(protect)"). None = PROT ignored (default). Others suppress an
        # action on PROT=1 steps: 'no_zero' (don't clear ACC), 'no_memwrite', 'no_regwrite', 'no_accum'.
        self.prot_mode = None
        self.free_reset()                   # Phase-1 MAC state: ACCf / RESf / _pend
        self.CPCf = 0                       # free-run CPC (per-sample position); separate from single-step CPC
        self.DABf = 0                       # free-run DAB (hold-last)
        self.XREGf = 0
        self.step_count = 0
        self.sample_count = 0
        self.fault = None

    # ---- one microinstruction (one WCS step), edge-driven MAC + §2T routing ----
    def free_step(self, l0, l1, l2, l3, audio_in, addr_offset=None, probe=None):
        d = decode(l2, l3)
        prot = (l2 >> 6) & 1                              # PROT = MI22 (§G3R); effect untraced
        ofst = ((l1 << 8) | l0) & 0xFFFF
        dev = FR.device_decode(d, ofst)

        # operand read BEFORE the regfile write (ARUCK@MS6 reads operand before the MS7 write).
        opnd = s16(self.R[d["RA"]].q)
        # optional XFER-gating hypothesis (see __init__): suppress the result-reg load on some steps.
        xfer_eff = d["XFER"]
        if self.xfer_gate is not None and d["XFER"]:
            xfer_eff = 1 if self.xfer_gate(d, dev) else 0
        # optional PROT hypothesis: suppress an action on PROT=1 steps.
        zero_eff = d["ZERO"]
        if prot and self.prot_mode == "no_zero":
            zero_eff = 0
        # SUB-SLOT deferred MAC: the 74LS163 accumulator (synchronous clear) + 74F374 result register,
        # driven by the EMERGENT per-slot strobes (ZERO/, XFER CK gated by ARUCKE/, ARUCKE/) from MC —
        # so the result-register capture-vs-clear timing EMERGES, not asserted. (Reproduces the deferred
        # MAC 300/300; the ARUCKE/-gated XFER CK does not change capture-before-clear.)
        self.mac_step_subslot(opnd, d["cmag"], d["CSIGN"], xfer_eff, zero_eff)

        # DMEM address — POST-verified convention addr = CPC + ofst + 1 = CPC − OFST (§3.6/§5.2).
        if addr_offset is not None:
            addr = (self.CPCf + addr_offset) & 0xFFFF
        else:
            addr = (self.CPCf + ofst + 1) & 0xFFFF
        dmem_old = self.DM.get(addr, 0)

        # drive the DAB — exactly one source per §2T device decode, else hold last (no pull resistors).
        drv = dev["driver"]
        if drv == FR.DRV_MEMR:
            self.DABf = dmem_old & 0xFFFF
        elif drv == FR.DRV_RDRREG:
            self.DABf = self.RESf & 0xFFFF
        elif drv == FR.DRV_RD_AD:
            self.DABf = FR.fpc_input_float_to_fixed(audio_in) if self.fpc_enabled else (audio_in & 0xFFFF)
        elif drv == FR.DRV_RD_XREG:
            self.DABf = 0                                    # host writes no X-data during audio free-run
        # DRV_HOLD: leave self.DABf unchanged

        # consume the DAB: regfile write R[WA] <- DAB @ DAB WSTB (¬MS7), every step.
        if not (prot and self.prot_mode == "no_regwrite"):
            self.R[d["WA"]].load(s16(self.DABf))
        # DMEM write (MEMW/): DIN = DAB (= result reg on a MEMW step, RDRREG drives the DAB).
        if dev["memwrite"] and not (prot and self.prot_mode == "no_memwrite"):
            self.DM[addr] = self.DABf & 0xFFFF
        # X-register + D/A output capture.
        out_da = []
        if dev["wr_xreg"]:
            self.XREGf = self.DABf & 0xFFFF
        if dev["wr_da"]:
            ov = FR.fpc_output_fixed_to_float(self.DABf) if self.fpc_enabled else s16(self.DABf)
            out_da = [(c, ov) for c in dev["da_chans"]]

        self.step_count += 1
        if probe is not None:
            probe.append(dict(d=d, ofst=ofst, addr=addr, drv=drv, dab=self.DABf & 0xFFFF,
                              opnd=opnd, ACC=self.ACCf, RES=self.RESf, memwrite=dev["memwrite"],
                              out_da=out_da, R=[r.q for r in self.R], CPC=self.CPCf))
        return out_da

    # ---- one audio sample = `modulus` microinstructions, then CPC += 1 at RESET ----
    def run_sample(self, wcs, audio_in, offsets=None, probe=None):
        outs = []
        for k in range(self.modulus):
            l0, l1, l2, l3 = wcs[k]
            ao = offsets[k] if offsets is not None else None
            outs.extend(self.free_step(l0, l1, l2, l3, audio_in & 0xFFFF, addr_offset=ao, probe=probe))
        self.CPCf = (self.CPCf + 1) & 0xFFFF                 # RESET: CPC advances one sample position
        self.sample_count += 1
        return outs

    # ---- run N samples, capture per-channel D/A (mirrors aru_freerun.run_free) ----
    def run_free(self, wcs, input_signal, n_samples, offsets=None, probe_first=0):
        chans = {c: [] for c in "ABCD"}
        mono = []
        all_probe = []
        for sidx in range(n_samples):
            ai = input_signal(sidx) if callable(input_signal) else (
                input_signal[sidx] if sidx < len(input_signal) else 0)
            probe = [] if sidx < probe_first else None
            outs = self.run_sample(wcs, ai & 0xFFFF, offsets=offsets, probe=probe)
            if probe is not None:
                all_probe.append(probe)
            persamp = {c: None for c in "ABCD"}
            ssum = 0
            for chan, val in outs:
                ssum += val
                persamp["ABCD"[chan & 3]] = val
            for c in "ABCD":
                chans[c].append(persamp[c] if persamp[c] is not None else 0)
            mono.append(ssum)
            if self.fault:
                break
        return dict(A=chans["A"], B=chans["B"], C=chans["C"], D=chans["D"], mono=mono, probe=all_probe)


# ===========================================================================
# Phase 2 self-tests
# ===========================================================================
def test_oracle_match_vs_freerun(n=400):
    """2.5 free-run oracle — the edge-driven FreeRunRTL must reproduce aru_freerun.FreeRunARU on the
    SETTLED per-sample D/A output (device decode + offset + single-tap recirc + deferred MAC), since
    Phase-1 mac_step reproduces aru_freerun's MAC and the routing is harvested. (Phase 3 DMEM timing is
    where they are DESIGNED to diverge — not here.)"""
    import aru_freerun as FRB
    # a hand-built comb program (from aru_freerun.test_feedback_comb) exercises MEMR/MEMW/IO/MAC together.
    D, g = 50, 16
    wcs = list([FR.nop_step()] * 128)
    wcs[0] = FR.encode_io_step(rd="AD", WA=0, RA=3, cmag=0)
    wcs[1] = FR.encode_step(offset=D, MEMAC=1, MI16=1, WA=1, RA=3, CSIGN=1, XFER=0, ZERO=1, cmag=0)
    wcs[2] = FR.encode_step(MEMAC=0, MI16=0, WA=3, RA=0, CSIGN=1, XFER=0, ZERO=0, cmag=32)
    wcs[3] = FR.encode_step(MEMAC=0, MI16=0, WA=3, RA=1, CSIGN=1, XFER=1, ZERO=0, cmag=g)
    wcs[4] = FR.encode_step(offset=0, MEMAC=1, MI16=0, WA=2, RA=2, CSIGN=1, cmag=0)
    wcs[5] = FR.encode_io_step(rd=None, wr_da=True, da_chan=0)

    def impulse(sidx):
        return 8000 if sidx == 0 else 0

    ref = FRB.FreeRunARU().run_free(wcs, impulse, n)
    got = FreeRunRTL(modulus=100).run_free(wcs, impulse, n)
    same = all(ref[c] == got[c] for c in "ABCD")
    # report first divergence if any
    if not same:
        for c in "ABCD":
            if ref[c] != got[c]:
                i = next(j for j in range(n) if ref[c][j] != got[c][j])
                print(f"    ch{c} diverges @sample {i}: ref={ref[c][i]} rtl={got[c][i]}")
                break
    print(f"2.5 oracle match FreeRunRTL vs aru_freerun (comb, {n} samples): "
          f"{'IDENTICAL' if same else 'DIVERGES'} [{'OK' if same else 'FAIL'}]")
    return same


def test_m3_feedback_comb(D=50, g_cmag=16, n=400):
    """2.4 M3 capability — the free-run datapath produces a clean decaying comb y[n]=x[n]+0.5·y[n−D].
    Measured structurally here (echo ladder + decay); the reverb_metrics WET/SPARSE check is in
    tools/aru_whole via the milestone harness."""
    wcs = list([FR.nop_step()] * 128)
    wcs[0] = FR.encode_io_step(rd="AD", WA=0, RA=3, cmag=0)
    wcs[1] = FR.encode_step(offset=D, MEMAC=1, MI16=1, WA=1, RA=3, CSIGN=1, XFER=0, ZERO=1, cmag=0)
    wcs[2] = FR.encode_step(MEMAC=0, MI16=0, WA=3, RA=0, CSIGN=1, XFER=0, ZERO=0, cmag=32)
    wcs[3] = FR.encode_step(MEMAC=0, MI16=0, WA=3, RA=1, CSIGN=1, XFER=1, ZERO=0, cmag=g_cmag)
    wcs[4] = FR.encode_step(offset=0, MEMAC=1, MI16=0, WA=2, RA=2, CSIGN=1, cmag=0)
    wcs[5] = FR.encode_io_step(rd=None, wr_da=True, da_chan=0)

    def impulse(sidx):
        return 8000 if sidx == 0 else 0

    a = FreeRunRTL(modulus=100).run_free(wcs, impulse, n)["A"]
    echoes = [(k * D, a[k * D]) for k in range(min(6, n // D)) if k * D < n]
    decayed = all(abs(echoes[i + 1][1]) < abs(echoes[i][1]) for i in range(len(echoes) - 1)
                  if echoes[i][1] != 0)
    alive = sum(1 for v in a if abs(v) > 2)
    ok = decayed and alive >= 4 and a[0] != 0 and max(abs(v) for v in a) <= 40000
    print(f"2.4 M3 feedback comb y[n]=x[n]+{g_cmag}/32·y[n-{D}]: echoes={echoes} "
          f"decayed={decayed} alive={alive} [{'OK' if ok else 'FAIL'}]")
    return ok


if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    print("=" * 74)
    print("224XL Phase 2 — T&C free-run on the edge-driven datapath (FreeRunRTL)")
    print("=" * 74)
    ok = True
    ok &= test_oracle_match_vs_freerun()
    ok &= test_m3_feedback_comb()
    print("-" * 74)
    print(f"PHASE 2 STRUCTURAL TESTS: {'ALL OK' if ok else 'FAILED'}")
    print("(POST unchanged — inherited single_step; run: python tools/aru_rtl_dp.py)")
